sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.2
node_js:
  - 4.1

env:
  - JEKYLL_ENV=production

before_install:
  - bundle install
  - npm install
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - bundle exec jekyll build
  - node_modules/jshint/bin/jshint _assets/js/
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr / - ; fi`
  - docker build -t sqroot/sqroot.eu:$TAG .
  - docker push sqroot/sqroot.eu:$TAG
  - docker rmi sqroot/sqroot.eu:$TAG

after_script:
  - docker logout

notifications:
  email:
    recipients:
      - alert@westfall.sqroot.eu
