# Site settings
title: SQroot
header-img: content/site/home-bg.jpg
email: ando@sqroot.eu
description: "A personal blog about IT & life"
baseurl: ""
url: "http://localhost:4000"
twitter_username: SQrooted
github_username:  anroots
facebook_username:
timezone: Europe/Tallinn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: "/:year/:month/:title"
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

assets:
  sources:
    - _assets/js
    - _assets/css
    - _assets/lib
  js_compressor: uglifier
  css_compressor: sass

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "Ando"
      comments: false
      layout: "post"
picture:
  source: "content"
  output: "content/generated"
  markup: "picture"
  presets:
    gallery:
      attr:
        class: "gallery img-thumbnail"
      source_default:
        width: 300
    default:
      ppi: [1, 1.5]
      source_large:
        media: "(min-width: 60em)"
        width: 1200
      source_medium:
        media: "(min-width: 40em) and (max-width: 60em)"
        width: 960
      source_small:
        media: "(min-width: 20em) and (max-width: 40em)"
        width: 600
      source_default: 
        width: 300