# Site settings
title: SQroot.eu
header-img: content/site/home-bg.jpg
email: ando@sqroot.eu
description: "A personal engineering blog"
baseurl: ""
url: "https://sqroot.eu"
timezone: Europe/Tallinn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: "/:year/:title"
paginate: 15
exclude: ["Gemfile", ".idea", "Gemfile.lock", "nginx.conf", "Dockerfile", "package.json", "LICENSE","README.md",".travis.yml", "vendor", "node_modules"]
include: [".well-known"]

plugins:
  - jekyll-paginate
  - jekyll-responsive-image  

assets:
  sources:
    - _assets/js
    - _assets/css
    - _assets/lib
    - content
    - node_modules
  js_compressor: uglifier
  css_compressor: sass

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 576  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 768
    - width: 992
      quality: 90
    - width: 1200
  base_path: content
  output_path_format: content/resized/%{width}/%{basename}


compress_html:
  ignore:
    envs:
      - development
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "Ando"
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      visible: true
