# Site settings
title: SQroot.eu
header-img: content/site/home-bg.jpg
email: ando@sqroot.eu
description: "A personal blog about information technology and society"
baseurl: ""
url: "https://sqroot.eu"
timezone: Europe/Tallinn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: "/:year/:title"
paginate: 15
exclude: ["Gemfile","Gemfile.lock", "nginx.conf", "Dockerfile", "package.json", "LICENSE","README.md",".travis.yml", "vendor", "node_modules"]

gems:
  - jekyll-paginate

assets:
  sources:
    - _assets/js
    - _assets/css
    - _assets/lib
  js_compressor: uglifier
  css_compressor: sass

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "Ando"
      comments: true
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      visible: true
picture:
  source: "content"
  output: "content/generated"
  markup: "picture"
  presets:
    gallery:
      attr:
        class: "gallery img-thumbnail"
      source_default:
        width: 300
      ppi: [1, 1.5]
      source_large:
        media: "(min-width: 60em)"
        width: 1200
      source_medium:
        media: "(min-width: 40em) and (max-width: 60em)"
        width: 960
      source_small:
        media: "(min-width: 20em) and (max-width: 40em)"
        width: 600
    default:
      ppi: [1, 1.5]
      source_large:
        media: "(min-width: 60em)"
        width: 1200
      source_medium:
        media: "(min-width: 40em) and (max-width: 60em)"
        width: 960
      source_small:
        media: "(min-width: 20em) and (max-width: 40em)"
        width: 600
      source_default: 
        width: 300